create table IF NOT EXISTS MORTGAGERATE
(
    ID             DECFLOAT(40) auto_increment
        primary key,
    INTERESTRATE   DOUBLE PRECISION,
    MATURITYPERIOD DECFLOAT(40),
    LASTUPDATED    TIMESTAMP
);
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (10.0,1,now());
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (7.0,3,TIMESTAMP WITH TIME ZONE '2025-08-09 12:30:000');
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (2.0,4,now());
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (3.5,6,TIMESTAMP WITH TIME ZONE '2025-02-10 12:30:000');
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (3.56,10,TIMESTAMP WITH TIME ZONE '2025-05-05 12:30:000');
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (6.6,32,TIMESTAMP WITH TIME ZONE '2025-01-12 12:30:000');
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (5.77,8,null);
insert into MORTGAGERATE (INTERESTRATE, MATURITYPERIOD, LASTUPDATED) values (1.0,122,TIMESTAMP WITH TIME ZONE '2025-08-10 12:30:000');

